algoritmo "semnome"

// Autor : Miguel Porto
// Data : 13/04/2026
// Aperte F9 para fazer funcionar

var
     idade: real


inicio

      escreval ("Vamos ver se você pode dirigir")
      escreval ("Digite sua idade")
      leia (idade)
      
      se idade >=18  entao
         escreva ("Você é maior de idade, pode dirigir")
         senao
              escreva ("Você não é maior de idade, não pode dirigir")
              fimse
// Seção de Comandos 
fimalgoritmo
