algoritmo "semnome"

// Autor : Miguel Porto
// Data : 13/04/2026
// Aperte F9 para fazer funcionar

var
     nome: literal
     senha: literal


inicio

      escreval ("Digite seu nome para acessar o site")
      leia (nome)
      
      escreval ("Digite a senha")
      leia (senha)
      
      se senha="abc23" entao
         escreval ("Senha correta")
      senao
           escreval ("Senha incorreta")
      fimse
      

fimalgoritmo
