algoritmo "Soma de três números"

// Autor :  Miguel Porto
// Data : 13/04/2026
// Aperte F9  para funcionar

var

   numeroUm, numeroDois, numeroTres, soma: real
inicio
// Bora lá

   escreval ("Vamos fazer a soma de três números")
   escreval ("Digite o primeiro número para a soma ")
   leia (numeroUm)
   
   escreva ("Digite o segundo número ")
   leia (numeroDois)
   
   escreva ("Digite o terceiro número ")
   leia (numeroTres)
   
//Vamos fazer a soma agr

        soma <- numeroUm + numeroDois + numeroTres
        
        escreval ("O resultado da soma foi ", soma)
fimalgoritmo
